### ISSUE TITLE
Feature request: search by description

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/appeals-app#14]
A power user of the application [has requested](https://twitter.com/jongeeting/status/1064903823502774272) the ability to search zoning appeals by the description field. It looks like this is possible but we'd probably want the search field to query multiple [fields](https://cityofphiladelphia.github.io/carto-api-explorer/#li_appeals) (like address) while we're at it. But probably a reasonable feature request. What do you think @alejandroxlopez and @CityOfPhiladelphia/l-i ?

Perhaps a short-term alternative would be to create a vizwit page for the `li_appeals` table (like [the one for permits](https://data.phila.gov/visualizations/li-building-permits)) but you wouldn't be able to filter by all the different polygons the zoning appeals app features.

**Comment by karissademi** [comment]
You can do this!

**Comment by timwis** [comment]
haha, I read this as "you can [implement] this [yourself]!" but now I realise you meant that it's been implemented! woot!

**Comment by karissademi** [comment]
Haha! I can see why you would have read it that way 😂
