### ISSUE TITLE
"Location History" Link is Broken

### ISSUE THREAD

**Issue by noahlee826** [CityOfPhiladelphia/appeals-app#29]
When viewing an appeal, Clicking the "Location History" link brings you to an Access Denied XML page that's missing a stylesheet.

Example Appeal: [https://www.phila.gov/li/appeals-calendar/#/appeals/36957](https://www.phila.gov/li/appeals-calendar/#/appeals/36957) 
The Location History link points to: [http://li.phila.gov/&_ga=2.214431711.935618296.1562084219-320138463.1551365272#summary?address=7828%20CHELWYNDE%20AVE](http://li.phila.gov/&_ga=2.214431711.935618296.1562084219-320138463.1551365272#summary?address=7828%20CHELWYNDE%20AVE)
Which looks like: 
![image](https://user-images.githubusercontent.com/15258656/60529783-58928b00-9cc5-11e9-92c8-d4a3f0330df4.png)

**Comment by karissademi** [comment]
Thanks for reporting! 

This was an issue with our Google Analytics setup and has now been resolved.
